services:
  mongo:
    image: mongo:7
    container_name: tpi_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: tpi_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  neo4j:
    image: neo4j:5
    container_name: tpi_neo4j
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      NEO4J_AUTH: neo4j/neo4j123
    volumes:
      - neo4j_data:/data

  cassandra:
    image: cassandra:4
    container_name: tpi_cassandra
    ports:
      - '9042:9042'
    environment:
      CASSANDRA_CLUSTER_NAME: tpi_cluster
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  mongo_data:
  redis_data:
  neo4j_data:
  cassandra_data: