services:
  app:
    build: .
    container_name: tpi_app
    ports:
      - '8050:8050'
    environment:
      MONGO_URI: mongodb://mongo:27017/
      MONGO_DB: tendencias_db
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
      CASSANDRA_KEYSPACE: tendencias
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: neo4j123
      DASHBOARD_HOST: 0.0.0.0
      DASHBOARD_PORT: 8050
    depends_on:
      - mongo
      - redis
      - neo4j
      - cassandra

  mongo:
    image: mongo:7
    container_name: tpi_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: tpi_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  neo4j:
    image: neo4j:5
    container_name: tpi_neo4j
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      NEO4J_AUTH: neo4j/neo4j123
    volumes:
      - neo4j_data:/data

  cassandra:
    image: cassandra:4
    container_name: tpi_cassandra
    ports:
      - '9042:9042'
    environment:
      CASSANDRA_CLUSTER_NAME: tpi_cluster
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  mongo_data:
  redis_data:
  neo4j_data:
  cassandra_data:
